### ISSUE TITLE
Listener enter/exit wrong declared

### ISSUE THREAD

**Issue by Patrick-Remy** [mcchatman8009/antlr4-tool#19] opened 2018-10-02 17:04 UTC
The listener definition file declares the listener methods by the pattern "ruleEnter"/"ruleExit", but the js source shows that they are defined as "enterRule"/"exitRule".

**Comment by johnholliday** [comment] 2018-10-03 11:11
The problem is this line:

https://github.com/mcchatman8009/antlr4-tool/blob/ff09417f031c69f00331c6c0936cd8a4796cb2a4/src/antlr-core/antlr-compiler.ts#L47

**Comment by mcchatman8009** [comment] 2018-10-15 17:37
@johnholliday this has been resolved with your pull request. 

Thanks

**Closed by mcchatman8009** 2018-10-15 17:37 UTC
